//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FormUI", typeof(FormUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account management.
        /// </summary>
        public static string AccountManagement {
            get {
                return ResourceManager.GetString("AccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuộc tính.
        /// </summary>
        public static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Name.
        /// </summary>
        public static string AttributeName {
            get {
                return ResourceManager.GetString("AttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị thuộc tính.
        /// </summary>
        public static string AttributeValue {
            get {
                return ResourceManager.GetString("AttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banners.
        /// </summary>
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Type.
        /// </summary>
        public static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangeFile {
            get {
                return ResourceManager.GetString("ChangeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color hex value.
        /// </summary>
        public static string ColorHex {
            get {
                return ResourceManager.GetString("ColorHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        public static string ContactInfomation {
            get {
                return ResourceManager.GetString("ContactInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact type.
        /// </summary>
        public static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current address.
        /// </summary>
        public static string CurrentAddress {
            get {
                return ResourceManager.GetString("CurrentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current menu.
        /// </summary>
        public static string CurrentMenu {
            get {
                return ResourceManager.GetString("CurrentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string DateOfBith {
            get {
                return ResourceManager.GetString("DateOfBith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete unsuccess.
        /// </summary>
        public static string DeleteFail {
            get {
                return ResourceManager.GetString("DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successful.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm giá.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Date.
        /// </summary>
        public static string DisplayDate {
            get {
                return ResourceManager.GetString("DisplayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display list items.
        /// </summary>
        public static string DisplayListItem {
            get {
                return ResourceManager.GetString("DisplayListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display on home page.
        /// </summary>
        public static string DisplayOnHomePage {
            get {
                return ResourceManager.GetString("DisplayOnHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị trên danh mục.
        /// </summary>
        public static string DisplayOnMenu {
            get {
                return ResourceManager.GetString("DisplayOnMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Districts.
        /// </summary>
        public static string Districts {
            get {
                return ResourceManager.GetString("Districts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SSL.
        /// </summary>
        public static string EnableSSL {
            get {
                return ResourceManager.GetString("EnableSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Retarget Snippet.
        /// </summary>
        public static string FacebookRetargetSnippet {
            get {
                return ResourceManager.GetString("FacebookRetargetSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favicon.
        /// </summary>
        public static string Favicon {
            get {
                return ResourceManager.GetString("Favicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Admin Id.
        /// </summary>
        public static string FbAdminsId {
            get {
                return ResourceManager.GetString("FbAdminsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook App Id.
        /// </summary>
        public static string FbAppId {
            get {
                return ResourceManager.GetString("FbAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy trình.
        /// </summary>
        public static string FlowStep {
            get {
                return ResourceManager.GetString("FlowStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer content.
        /// </summary>
        public static string FooterContent {
            get {
                return ResourceManager.GetString("FooterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From address.
        /// </summary>
        public static string FromAddress {
            get {
                return ResourceManager.GetString("FromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromDate.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google map.
        /// </summary>
        public static string GoogleMap {
            get {
                return ResourceManager.GetString("GoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Retarget Snippet.
        /// </summary>
        public static string GoogleRetargetSnippet {
            get {
                return ResourceManager.GetString("GoogleRetargetSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home display.
        /// </summary>
        public static string HomeDisplay {
            get {
                return ResourceManager.GetString("HomeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotline.
        /// </summary>
        public static string Hotline {
            get {
                return ResourceManager.GetString("Hotline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageUrl {
            get {
                return ResourceManager.GetString("ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InStock.
        /// </summary>
        public static string InStock {
            get {
                return ResourceManager.GetString("InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lag.
        /// </summary>
        public static string Lag {
            get {
                return ResourceManager.GetString("Lag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageCode.
        /// </summary>
        public static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageName.
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat.
        /// </summary>
        public static string Lat {
            get {
                return ResourceManager.GetString("Lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocaleValue.
        /// </summary>
        public static string LocaleValue {
            get {
                return ResourceManager.GetString("LocaleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string LogoImage {
            get {
                return ResourceManager.GetString("LogoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site maintance.
        /// </summary>
        public static string MaintanceSite {
            get {
                return ResourceManager.GetString("MaintanceSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string MenuLink {
            get {
                return ResourceManager.GetString("MenuLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta description.
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta keywords.
        /// </summary>
        public static string MetaKeywords {
            get {
                return ResourceManager.GetString("MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTag Master Tool.
        /// </summary>
        public static string MetaTagMasterTool {
            get {
                return ResourceManager.GetString("MetaTagMasterTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta title.
        /// </summary>
        public static string MetaTitle {
            get {
                return ResourceManager.GetString("MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone.
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string NewsManagement {
            get {
                return ResourceManager.GetString("NewsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng quà tặng.
        /// </summary>
        public static string NumberOfGift {
            get {
                return ResourceManager.GetString("NumberOfGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thứ tự.
        /// </summary>
        public static string NumberOfStore {
            get {
                return ResourceManager.GetString("NumberOfStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP mới/Cũ?.
        /// </summary>
        public static string OldOrNew {
            get {
                return ResourceManager.GetString("OldOrNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display options.
        /// </summary>
        public static string OptionDisplay {
            get {
                return ResourceManager.GetString("OptionDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order display.
        /// </summary>
        public static string OrderDisplay {
            get {
                return ResourceManager.GetString("OrderDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other address.
        /// </summary>
        public static string OtherAddress {
            get {
                return ResourceManager.GetString("OtherAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết hàng.
        /// </summary>
        public static string OutOfStock {
            get {
                return ResourceManager.GetString("OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageBanner.
        /// </summary>
        public static string PageBanner {
            get {
                return ResourceManager.GetString("PageBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page name.
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent menu.
        /// </summary>
        public static string ParentMenu {
            get {
                return ResourceManager.GetString("ParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string PostManagement {
            get {
                return ResourceManager.GetString("PostManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post type.
        /// </summary>
        public static string PostType {
            get {
                return ResourceManager.GetString("PostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product code.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán chạy.
        /// </summary>
        public static string ProductHot {
            get {
                return ResourceManager.GetString("ProductHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm mới.
        /// </summary>
        public static string ProductNew {
            get {
                return ResourceManager.GetString("ProductNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provinces.
        /// </summary>
        public static string Provinces {
            get {
                return ResourceManager.GetString("Provinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher GooglePlus.
        /// </summary>
        public static string PublisherGooglePlus {
            get {
                return ResourceManager.GetString("PublisherGooglePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấp quyền.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select map.
        /// </summary>
        public static string SelectMap {
            get {
                return ResourceManager.GetString("SelectMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seo link.
        /// </summary>
        public static string SeoUrl {
            get {
                return ResourceManager.GetString("SeoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt mail.
        /// </summary>
        public static string ServerMailSetting {
            get {
                return ResourceManager.GetString("ServerMailSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt SEO.
        /// </summary>
        public static string SettingSeoGlobal {
            get {
                return ResourceManager.GetString("SettingSeoGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string ShopId {
            get {
                return ResourceManager.GetString("ShopId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description.
        /// </summary>
        public static string ShortDesc {
            get {
                return ResourceManager.GetString("ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display content.
        /// </summary>
        public static string ShowContent {
            get {
                return ResourceManager.GetString("ShowContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide.
        /// </summary>
        public static string SlideShow {
            get {
                return ResourceManager.GetString("SlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp client.
        /// </summary>
        public static string SmtpClient {
            get {
                return ResourceManager.GetString("SmtpClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string SMTPPort {
            get {
                return ResourceManager.GetString("SMTPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Google Analytics.
        /// </summary>
        public static string SnippetGoogleAnalytics {
            get {
                return ResourceManager.GetString("SnippetGoogleAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source link.
        /// </summary>
        public static string SourceLink {
            get {
                return ResourceManager.GetString("SourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special display.
        /// </summary>
        public static string SpecialDisplay {
            get {
                return ResourceManager.GetString("SpecialDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung tĩnh.
        /// </summary>
        public static string StaticContent {
            get {
                return ResourceManager.GetString("StaticContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt hệ thống.
        /// </summary>
        public static string SystemSetting {
            get {
                return ResourceManager.GetString("SystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Template.
        /// </summary>
        public static string TemplateNews {
            get {
                return ResourceManager.GetString("TemplateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Template.
        /// </summary>
        public static string TemplateProduct {
            get {
                return ResourceManager.GetString("TemplateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Content.
        /// </summary>
        public static string TemplateStatic {
            get {
                return ResourceManager.GetString("TemplateStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string TemplateType {
            get {
                return ResourceManager.GetString("TemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time work.
        /// </summary>
        public static string TimeWork {
            get {
                return ResourceManager.GetString("TimeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDate.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu type.
        /// </summary>
        public static string TypeMenu {
            get {
                return ResourceManager.GetString("TypeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuộc tính.
        /// </summary>
        public static string ValueName {
            get {
                return ResourceManager.GetString("ValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video link.
        /// </summary>
        public static string VideoLink {
            get {
                return ResourceManager.GetString("VideoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website link.
        /// </summary>
        public static string WebsiteLink {
            get {
                return ResourceManager.GetString("WebsiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
