//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityValidateResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityValidateResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.IdentityValidateResource", typeof(IdentityValidateResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a phone number..
        /// </summary>
        public static string AddPhoneNumber_SubTitle {
            get {
                return ResourceManager.GetString("AddPhoneNumber_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number..
        /// </summary>
        public static string AddPhoneNumber_Title {
            get {
                return ResourceManager.GetString("AddPhoneNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security code id: {0}.
        /// </summary>
        public static string AddPhoneNumberCtrl_SecurityCodeMessage {
            get {
                return ResourceManager.GetString("AddPhoneNumberCtrl_SecurityCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Role.
        /// </summary>
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account password..
        /// </summary>
        public static string ChangePassword_SubTitle {
            get {
                return ResourceManager.GetString("ChangePassword_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password..
        /// </summary>
        public static string ChangePassword_Title {
            get {
                return ResourceManager.GetString("ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string ChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to login.
        /// </summary>
        public static string ClickHereToLogin {
            get {
                return ResourceManager.GetString("ClickHereToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not exceed {1} characters.
        /// </summary>
        public static string Company_Length {
            get {
                return ResourceManager.GetString("Company_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of your company or the organisation that you work for.
        /// </summary>
        public static string Company_Required {
            get {
                return ResourceManager.GetString("Company_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;A confirmation email has been sent to your &lt;strong&gt;{0}&lt;/strong&gt; email address.&lt;/p&gt;
        ///&lt;p&gt;Please click on the link within the email to confirm your email address.&lt;/p&gt;
        ///&lt;p&gt;Once you have confirmed your email address you will be able to login.&lt;/p&gt;.
        /// </summary>
        public static string ConfirmationEmailSent_Message {
            get {
                return ResourceManager.GetString("ConfirmationEmailSent_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearly there..
        /// </summary>
        public static string ConfirmationEmailSent_Title {
            get {
                return ResourceManager.GetString("ConfirmationEmailSent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Thank you for confirming your email address.  All you need to do now is &lt;a href=&quot;{0}&quot;&gt;login&lt;/a&gt;..
        /// </summary>
        public static string ConfirmEmail_ThankYou {
            get {
                return ResourceManager.GetString("ConfirmEmail_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email Address..
        /// </summary>
        public static string ConfirmEmail_Title {
            get {
                return ResourceManager.GetString("ConfirmEmail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hold on there - you must confirm your email address before you can login.&lt;/p&gt;.
        /// </summary>
        public static string ConfirmEmailBeforeLogin_Message {
            get {
                return ResourceManager.GetString("ConfirmEmailBeforeLogin_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold On!.
        /// </summary>
        public static string ConfirmEmailBeforeLogin_Title {
            get {
                return ResourceManager.GetString("ConfirmEmailBeforeLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops - your passwords do not match.
        /// </summary>
        public static string ConfirmPassword_Compare {
            get {
                return ResourceManager.GetString("ConfirmPassword_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, that looks like an invalid email address format.
        /// </summary>
        public static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address.
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed?.
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Link.
        /// </summary>
        public static string EmailLink {
            get {
                return ResourceManager.GetString("EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your {0} account..
        /// </summary>
        public static string ExternalLoginConfirmation_AssociateAccount {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation_AssociateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Association.
        /// </summary>
        public static string ExternalLoginConfirmation_AssociationForm {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation_AssociationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with &lt;strong&gt;{0}&lt;/strong&gt;. Please enter a user name for this site below and click the Register button to finish logging in..
        /// </summary>
        public static string ExternalLoginConfirmation_AuthenticationSuccess {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation_AuthenticationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register..
        /// </summary>
        public static string ExternalLoginConfirmation_Title {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with remote service..
        /// </summary>
        public static string ExternalLoginFailure_FailureMessage {
            get {
                return ResourceManager.GetString("ExternalLoginFailure_FailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure..
        /// </summary>
        public static string ExternalLoginFailure_Title {
            get {
                return ResourceManager.GetString("ExternalLoginFailure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Logins.
        /// </summary>
        public static string ExternalLogins {
            get {
                return ResourceManager.GetString("ExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication providers registered at this time.
        /// </summary>
        public static string ExternalLoginsList_NoProviders {
            get {
                return ResourceManager.GetString("ExternalLoginsList_NoProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to login..
        /// </summary>
        public static string ExternalLoginsList_Title {
            get {
                return ResourceManager.GetString("ExternalLoginsList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell us your first name.
        /// </summary>
        public static string FirstName_Required {
            get {
                return ResourceManager.GetString("FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Visit the
        ///    &lt;a href=&quot;{0}&quot;&gt;Account Management&lt;/a&gt;
        ///    page and enable Two-Factor Authentication.  Once enabled, a code
        ///    number will be sent to your email address or mobile phone every
        ///    time you login.  Once enabled, this will mechanism will further
        ///    improve your online security.
        ///&lt;/p&gt;.
        /// </summary>
        public static string FirstTimeLogin_2FA_Description {
            get {
                return ResourceManager.GetString("FirstTimeLogin_2FA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further secure your account with Two-Factor Authentication.
        /// </summary>
        public static string FirstTimeLogin_2FA_Title {
            get {
                return ResourceManager.GetString("FirstTimeLogin_2FA_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Now that you are a fully signed&amp;ndash;up user you might want to&amp;hellip;
        ///&lt;/p&gt;.
        /// </summary>
        public static string FirstTimeLogin_Introduction {
            get {
                return ResourceManager.GetString("FirstTimeLogin_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Link your UrfIdentity account to LinkedIn network. This will allow
        ///    you to conveniently login in the future using your LinkedIn
        ///    service.
        ///&lt;/p&gt;.
        /// </summary>
        public static string FirstTimeLogin_Link_Description {
            get {
                return ResourceManager.GetString("FirstTimeLogin_Link_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to your LinkedIn Account.
        /// </summary>
        public static string FirstTimeLogin_Link_Title {
            get {
                return ResourceManager.GetString("FirstTimeLogin_Link_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Time Login.
        /// </summary>
        public static string FirstTimeLogin_Title {
            get {
                return ResourceManager.GetString("FirstTimeLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address..
        /// </summary>
        public static string ForgotPassword_SubTitle {
            get {
                return ResourceManager.GetString("ForgotPassword_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string ForgotPasswordConfirmation_ReminderMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation_ReminderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation..
        /// </summary>
        public static string ForgotPasswordConfirmation_Title {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by clicking &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;..
        /// </summary>
        public static string ForgotPasswordCtrl_Message {
            get {
                return ResourceManager.GetString("ForgotPasswordCtrl_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Access.
        /// </summary>
        public static string GetAccess {
            get {
                return ResourceManager.GetString("GetAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Password?.
        /// </summary>
        public static string HasPassword {
            get {
                return ResourceManager.GetString("HasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Authentication Enabled?.
        /// </summary>
        public static string HasTwoFactorAuthentication {
            get {
                return ResourceManager.GetString("HasTwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell us your job title.
        /// </summary>
        public static string JobTitle_Required {
            get {
                return ResourceManager.GetString("JobTitle_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login.
        /// </summary>
        public static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell us your last name.
        /// </summary>
        public static string LastName_Required {
            get {
                return ResourceManager.GetString("LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked-Out?.
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string Login_RegisterAsANewUser {
            get {
                return ResourceManager.GetString("Login_RegisterAsANewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In..
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your UrfIdentity local account to login..
        /// </summary>
        public static string Login_UseLocalAccount {
            get {
                return ResourceManager.GetString("Login_UseLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string LoginCtrl_InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("LoginCtrl_InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with LinkedIn.
        /// </summary>
        public static string LoginWithLinkedIn {
            get {
                return ResourceManager.GetString("LoginWithLinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings..
        /// </summary>
        public static string ManageIndex_SubTitle {
            get {
                return ResourceManager.GetString("ManageIndex_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account..
        /// </summary>
        public static string ManageIndex_Title {
            get {
                return ResourceManager.GetString("ManageIndex_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered logins..
        /// </summary>
        public static string ManageLogins_SubTitle {
            get {
                return ResourceManager.GetString("ManageLogins_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Your External Logins..
        /// </summary>
        public static string ManageLogins_Title {
            get {
                return ResourceManager.GetString("ManageLogins_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number has been added..
        /// </summary>
        public static string ManageMessageId_AddPhoneSuccess {
            get {
                return ResourceManager.GetString("ManageMessageId_AddPhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string ManageMessageId_ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ManageMessageId_ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string ManageMessageId_Error {
            get {
                return ResourceManager.GetString("ManageMessageId_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string ManageMessageId_RemoveLoginSuccess {
            get {
                return ResourceManager.GetString("ManageMessageId_RemoveLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number has been removed..
        /// </summary>
        public static string ManageMessageId_RemovePhoneSuccess {
            get {
                return ResourceManager.GetString("ManageMessageId_RemovePhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string ManageMessageId_SetPasswordSuccess {
            get {
                return ResourceManager.GetString("ManageMessageId_SetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your two-factor authentication provider has been set..
        /// </summary>
        public static string ManageMessageId_SetTwoFactorSuccess {
            get {
                return ResourceManager.GetString("ManageMessageId_SetTwoFactorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password must be between {1} and {2} characters in length.
        /// </summary>
        public static string NewPassword_Length {
            get {
                return ResourceManager.GetString("NewPassword_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify your new password.
        /// </summary>
        public static string NewPassword_Required {
            get {
                return ResourceManager.GetString("NewPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Roles have been defined!.
        /// </summary>
        public static string NoRolesHaveBeenDefined {
            get {
                return ResourceManager.GetString("NoRolesHaveBeenDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your UrfIdentity security code is {0}.
        /// </summary>
        public static string OAuth_Email_Body {
            get {
                return ResourceManager.GetString("OAuth_Email_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UrfIdentity Code.
        /// </summary>
        public static string OAuth_Email_Subject {
            get {
                return ResourceManager.GetString("OAuth_Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your UrfIdentity security code is {0}.
        /// </summary>
        public static string OAuth_SMS_Body {
            get {
                return ResourceManager.GetString("OAuth_SMS_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An authentication provider must be selected.
        /// </summary>
        public static string OAuthProvider_Required {
            get {
                return ResourceManager.GetString("OAuthProvider_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        public static string OAuthProviderList {
            get {
                return ResourceManager.GetString("OAuthProviderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} must be at least 8 characters long and contain at least: 1 uppercase character (A-Z), one lower-case character (a-z), one digit (0-9), one non-character/digit (e.g. _-$#!£).
        /// </summary>
        public static string Password_Format {
            get {
                return ResourceManager.GetString("Password_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your {0}.
        /// </summary>
        public static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your phone number.
        /// </summary>
        public static string Phone_Required {
            get {
                return ResourceManager.GetString("Phone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered phone number is invalid.
        /// </summary>
        public static string PhoneNumber_Invalid {
            get {
                return ResourceManager.GetString("PhoneNumber_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your phone number.
        /// </summary>
        public static string PhoneNumber_Required {
            get {
                return ResourceManager.GetString("PhoneNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only contain alpha-numeric characters, spaces and hyphens.
        /// </summary>
        public static string PlainString_Format {
            get {
                return ResourceManager.GetString("PlainString_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem adding Roles to user.
        /// </summary>
        public static string ProblemAddingRolesToUser {
            get {
                return ResourceManager.GetString("ProblemAddingRolesToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem removing Roles from user.
        /// </summary>
        public static string ProblemRemovingRolesFromUser {
            get {
                return ResourceManager.GetString("ProblemRemovingRolesFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string Register_SubTitle {
            get {
                return ResourceManager.GetString("Register_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register..
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Logins.
        /// </summary>
        public static string RegisteredLoginList {
            get {
                return ResourceManager.GetString("RegisteredLoginList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by clicking &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;..
        /// </summary>
        public static string RegisterEmailConfirmation_Message {
            get {
                return ResourceManager.GetString("RegisterEmailConfirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your account.
        /// </summary>
        public static string RegisterEmailConfirmation_Subject {
            get {
                return ResourceManager.GetString("RegisterEmailConfirmation_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this browser?.
        /// </summary>
        public static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Email Confirmation.
        /// </summary>
        public static string ResendEmailConfirmation {
            get {
                return ResourceManager.GetString("ResendEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your account password..
        /// </summary>
        public static string ResetPassword_SubTitle {
            get {
                return ResourceManager.GetString("ResetPassword_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password..
        /// </summary>
        public static string ResetPassword_Title {
            get {
                return ResourceManager.GetString("ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string ResetPasswordConfirmation_Link {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string ResetPasswordConfirmation_LinkEpilog {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation_LinkEpilog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string ResetPasswordConfirmation_LinkProlog {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation_LinkProlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password Confirmation..
        /// </summary>
        public static string ResetPasswordConfirmation_Title {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset..
        /// </summary>
        public static string ResetPasswordConfirmation_YourPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation_YourPasswordHasBeenReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return URL.
        /// </summary>
        public static string ReturnUrl {
            get {
                return ResourceManager.GetString("ReturnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &apos;{0}&apos; added successfully.
        /// </summary>
        public static string RoleAddedSuccessfully {
            get {
                return ResourceManager.GetString("RoleAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &apos;{0}&apos; already exists - request ignored!.
        /// </summary>
        public static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &apos;{0}&apos; deleted successfully.
        /// </summary>
        public static string RoleDeletedSuccessfully {
            get {
                return ResourceManager.GetString("RoleDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Manager.
        /// </summary>
        public static string RoleManager {
            get {
                return ResourceManager.GetString("RoleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleName.
        /// </summary>
        public static string RoleName_Placeholder {
            get {
                return ResourceManager.GetString("RoleName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code.
        /// </summary>
        public static string SecurityCode {
            get {
                return ResourceManager.GetString("SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the most recent security code sent to your account.
        /// </summary>
        public static string SecurityCode_Required {
            get {
                return ResourceManager.GetString("SecurityCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Provider.
        /// </summary>
        public static string SelectedOAuthProvider {
            get {
                return ResourceManager.GetString("SelectedOAuthProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification code..
        /// </summary>
        public static string SendCode_SubTitle {
            get {
                return ResourceManager.GetString("SendCode_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Code..
        /// </summary>
        public static string SendCode_Title {
            get {
                return ResourceManager.GetString("SendCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site.  Add a local account so you can log  in without an external login..
        /// </summary>
        public static string SetPassword_Message {
            get {
                return ResourceManager.GetString("SetPassword_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create local login..
        /// </summary>
        public static string SetPassword_SubTitle {
            get {
                return ResourceManager.GetString("SetPassword_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password..
        /// </summary>
        public static string SetPassword_Title {
            get {
                return ResourceManager.GetString("SetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested user was not found!.
        /// </summary>
        public static string TheRequestedUserWasNotFound {
            get {
                return ResourceManager.GetString("TheRequestedUserWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Authentication.
        /// </summary>
        public static string TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("TwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create Role &apos;{0}&apos;!.
        /// </summary>
        public static string UnableToCreateRole {
            get {
                return ResourceManager.GetString("UnableToCreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete Role &apos;{0}&apos;!.
        /// </summary>
        public static string UnableToDeleteRole {
            get {
                return ResourceManager.GetString("UnableToDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find requested Role - perhaps it has been deleted!.
        /// </summary>
        public static string UnableToFindRequestedRole {
            get {
                return ResourceManager.GetString("UnableToFindRequestedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Sorry, but we have not been able to resend an account confirmation email to your account.&lt;/p&gt;.
        /// </summary>
        public static string UnableToResendEmailConfirmation {
            get {
                return ResourceManager.GetString("UnableToResendEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You have attempted to login with your {0} account but unfortunately the user details are not associated a local UrfIdentity account.&lt;/p&gt;
        ///&lt;p&gt;You can either &lt;a href=&quot;{1}&quot;&gt;login&lt;/a&gt; using your existing UrfIdentity account and then associate your {0} login to your account &amp;ndash; this will make future logins more convenient, or &amp;hellip;  If you do not currently have an UrfIdentity account you can &lt;a href=&quot;{2}&quot;&gt;create one here&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string UnassignedExternalLogin_Message {
            get {
                return ResourceManager.GetString("UnassignedExternalLogin_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psst! Need an UrfIdentity Login?.
        /// </summary>
        public static string UnassignedExternalLogin_Title {
            get {
                return ResourceManager.GetString("UnassignedExternalLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        public static string User_Account {
            get {
                return ResourceManager.GetString("User_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string User_Role {
            get {
                return ResourceManager.GetString("User_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Manager.
        /// </summary>
        public static string UserManager {
            get {
                return ResourceManager.GetString("UserManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles updated successfully ({0} added/{1} removed).
        /// </summary>
        public static string UsersRolesUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UsersRolesUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code..
        /// </summary>
        public static string VerifyCode_SubTitle {
            get {
                return ResourceManager.GetString("VerifyCode_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify..
        /// </summary>
        public static string VerifyCode_Title {
            get {
                return ResourceManager.GetString("VerifyCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string VerifyCodeCtrl_InvalidCode {
            get {
                return ResourceManager.GetString("VerifyCodeCtrl_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code..
        /// </summary>
        public static string VerifyPhoneNumber_SubTitle {
            get {
                return ResourceManager.GetString("VerifyPhoneNumber_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number..
        /// </summary>
        public static string VerifyPhoneNumber_Title {
            get {
                return ResourceManager.GetString("VerifyPhoneNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify phone..
        /// </summary>
        public static string VerifyPhoneNumberCtrl_FailedToVerifyPhone {
            get {
                return ResourceManager.GetString("VerifyPhoneNumberCtrl_FailedToVerifyPhone", resourceCulture);
            }
        }
    }
}
